" ===================== "
"        Plugins
" ===================== "
call plug#begin('~/.vim/plugged')

" colorscheme
Plug 'joshdick/onedark.vim'

" Initialize plugin system
call plug#end()


"Enable syntax highlighting
syntax on

"Enable onedark as theme
colorscheme onedark
set background=dark

set number

imap jj <esc>
